github:
  prebuilds:
    master: false
    branches: false
tasks:
  - name: install dependencies
    init: |
      sudo apt install cmake -y
      sudo bash build.sh init
      echo -e "\033[32m\nDependency installed successfully\033[0m"